# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nginxclienttest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://yadhaptest1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bde6fa4a3c704f848150cedc3858cdac }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5a325561f623473fb31c3576962ff847 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: yadhaptest1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bde6fa4a3c704f848150cedc3858cdac }}/nginxtest_client:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nginxclienttest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87a4ed8b5f6049969f75a844f6e7981f }}
        images: 'yadhaptest1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bde6fa4a3c704f848150cedc3858cdac }}/nginxtest_client:${{ github.sha }}'