# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - clienttestnew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://nginxtestregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1ed4dd5bed5b4d759e8e284c7f61e35e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_768a85f9522742a89decae6864918306 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nginxtestregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1ed4dd5bed5b4d759e8e284c7f61e35e }}/nginxtestclient:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'clienttestnew'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a05ff2985154d36b7715918d374c691 }}
        images: 'nginxtestregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1ed4dd5bed5b4d759e8e284c7f61e35e }}/nginxtestclient:${{ github.sha }}'